In [1]:
import torch

#python list
a = [1.0, 2.0, 3.0]

In [2]:
a[0]

1.0

In [3]:
a

[1.0, 2.0, 3.0]

In [4]:
a = torch.ones(3)

In [5]:
a

tensor([1., 1., 1.])

In [6]:
points = torch.tensor([1.0, 2.0, 3.0], dtype=int)

<ipython-input-6-54c9c712bb94>:1: DeprecationWarning: an integer is required (got type float).  Implicit conversion to integers using __int__ is deprecated, and may be removed in a future version of Python.
  points = torch.tensor([1.0, 2.0, 3.0], dtype=int)


In [7]:
points

tensor([1, 2, 3])

In [8]:
double_points = torch.ones((10, 4), dtype=torch.double)

In [9]:
double_points

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]], dtype=torch.float64)

In [10]:
a = torch.ones(3, 2)

In [11]:
a_t = a.transpose(0, 1)

In [12]:
a_t

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [13]:
a

tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])

In [14]:
a.transpose(1, 0)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [15]:
torch.ones(4, 3)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [16]:
import numpy as np
np.ones((3, 2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [21]:
a = torch.tensor([[-0.8434, -1.2832,  3.8661, -2.5491,  1.5971, -1.3434,  2.9549, -6.8086,
         -1.7130, -1.8171]])

In [22]:
value, indice = torch.topk(a, 1)
print(indice)

tensor([[2]])
